apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: mlflow
      targetRevision: 0.17.0
      helm:
        valueFiles:
          - $values/platform/mlflow/values.yaml
    - repoURL: https://github.com/srinidatadevops/mlops-platform-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
